name: 'IOS Detox Test'

on: 
  push:
    branches:
      - "main"
  
  pull_request_review:
    types: [submitted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  e2e-android:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: Frontend/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('Frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install node_modules dependencies
        run: cd Frontend && npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
      
      # - name: Generate .env
      #   run: cd Frontend && echo 'BACKEND_URL_API="https://backend-rntl.onrender.com"' > .env

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # - name: Detox build
      #   run: cd Frontend && npx detox build --configuration android.emu.release

      - name: Detox rebuild framework cache
        run: cd Frontend && npm run detox:clear:build

      - name: Detox test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: default
          emulator-options: -dns-server 8.8.8.8
          script: cd Frontend && npm run test:detox:android:pipeline

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: detox-artifacts
          path: Frontend/artifacts/**/**/*
