name: 'IOS Detox Test'

on: 
  push:
    branches:
      - "main"
  
  pull_request_review:
    types: [submitted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  e2e-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: Frontend/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('Frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install node_modules dependencies
        run: cd Frontend && npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        
      # - name: Generate .env
      #   run: cd Frontend && echo 'BACKEND_URL_API="https://backend-rntl.onrender.com"' > .env

      - name: Install macOS dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '2.7'
      #     bundler-cache: true

      # - name: Cache CocoaPods
      #   id: cache-cocoapods
      #   uses: actions/cache@v3
      #   with:
      #     path: ios/Pods
      #     key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pods-

      # - name: Install CocoaPods
      #   if: steps.cache-cocoapods.outputs.cache-hit != 'true'
      #   run: cd Frontend/ios && pod install

      # - name: Cache Detox build
      #   id: cache-detox-build
      #   uses: actions/cache@v3
      #   with:
      #     path: ios/build
      #     key: ${{ runner.os }}-detox-build
      #     restore-keys: |
      #       ${{ runner.os }}-detox-build

      # - name: Detox build
      #   run: cd Frontend && npm run detox:build:ios

      - name: Detox rebuild framework cache
        run: cd Frontend && npm run detox:clear:build

      - name: Detox test
        run: cd Frontend && npm run detox:test:ios:pipeline

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: Frontend/artifacts/**/**/*