name: 'My First Workflow'

on: 
  push:
    branches:
      - "main"
  
  pull_request_review:
    types: [submitted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Git Action - Checkout
        uses: actions/checkout@v4
      
      - name: Git Action - Setup Node Enviroment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Custom Shell - Install Dependencies
        run: cd Frontend && npm install

      - name: Custom Shell - Running Unit Tests
        run: cd Frontend && npm run test

  e2e-android:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: cd Frontend && npm install
      
      - name: Generate .env
        run: cd Frontend && echo 'BACKEND_URL_API="https://backend-rntl.onrender.com"' > .env

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Detox build
        run: cd Frontend && npx detox build --configuration android.emu.release

      - name: Detox test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: playstore
          emulator-options: -dns-server 8.8.8.8
          script: cd Frontend && npm run test:detox:android:pipeline

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: detox-artifacts
          path: Frontend/artifacts/**/**/*